version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  build:
    working_directory: ~/repo
    executor: aws-cli/default
    steps: 
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  push:
    working_directory: ~/repo
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-cli/setup
      - run: aws codeartifact login --tool npm --repository $ARTIFACT_REPOSITORY --domain $ARTIFACT_DOMAIN
      - run: npm publish
workflows:
  build-and-push:
    jobs:
      - build
      - push:
          requires: 
            - build
          context: 
            - AWS
            - ARTIFACT